#!/bin/sh

CWD=`pwd`
TMP=`mktemp -p $CWD -q -t XXXXXXXX.tmp`
bzr ignored | sed -re s/^\(\[^\[:space:\]\]\+\).\*/\\1/\; | tee "$TMP" 1> /dev/null 2>&1
for victim in `cat "$TMP"`
do
	COMMAND="rm -r $victim"
	printf "$COMMAND\n"
	$COMMAND
done

rm "$TMP"
