#!/bin/sh

printf "$1"'\n' >> ./resources/updated.txt
sed -re 's,^(\./)*,,g' ./resources/updated.txt | sort | uniq | tee ./resources/lol
mv ./resources/lol ./resources/updated.txt
wc -l ./resources/updated.txt | sed -re 's,^[[:space:]]*([[:digit:]]+).*$, *** Updated files: \1,' 
